server:
  port: 8083
  
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://idp:9999/auth/realms/master
        registration:
          keycloak:
            client-id: master-realm
            client-secret: 53189bd9-8bf1-48a6-bc58-b7c566754846
            authorization-grant-type: client_credentials
  kafka:
    bootstrap-servers: localhost:9092
    consumer.group-id: tenants

keycloakUri: http://idp:9999/auth